#ifndef PARAMS_H
#define PARAMS_H

#define INIT_NUM_WORKERS  3
#define WRKR_LIMIT 20
#define RESOURCES_INIT_SIZE 20
#define WRKR_SIZE 2
#define RESOURCES_RENEW_SIZE 25
#define PLAYER_RESOURCES_INIT_SIZE 50
#define WRKR_COST 75
#define INIT_WRKR_HEALTH 3


#endif // PARAMS_H_INCLUDED
